version: '27.3.1'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medidb
    volumes:
      - ./data:/var/lib/postgresql/data