POST http://localhost:8080/vitaldaten/0f8052f5-be9c-4bab-b892-7b2fe1bae2c5
Content-Type: application/json

{
  "herzfrequenz": 90,
  "atemfrequenz": 10,
  "systolisch": 120,
  "diastolisch": 80,
  "temperatur": 36.5,
  "datum": "2023-10-10T10:00:00"
}