POST http://localhost:8080/vitaldaten/0dbd27be-5a19-42d5-b060-a0adff013ef7
Content-Type: application/json

{
  "herzfrequenz": 90,
  "atemfrequenz": 10,
  "systolisch": 120,
  "diastolisch": 80,
  "temperatur": 36.5,
  "datum": "2023-10-10T10:00:00"
}