POST http://localhost:8080/api/v1/vitaldaten/71f1ab8a-8df2-4984-a489-0c3d8084df08
Content-Type: application/json

{
  "vitaldaten": {
    "systolisch": 120,
    "diastolisch": 80,
    "puls": 80,
    "sauerstoff": 98,
    "temperatur": 36.5
  }
}