POST http://localhost:8080/vitaldaten/513532a9-918c-4f64-a435-c0016cd42be1
Content-Type: application/json

{
  "herzfrequenz": 80,
  "atemfrequenz": 20,
  "systolisch": 120,
  "diastolisch": 80,
  "temperatur": 36.5,
  "datum": "2023-10-10T10:00:00"
}