# Kontinuierliche Integration (CI)
name: Java CI mit Maven

# Ausführung: Push oder Pull Request auf Main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Ausführen des Auftrags
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        # Konfigurationsdatei pom.xml
        run: mvn -B package --file pom.xml

      # Abhängigkeitsdiagramm
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6