# Kontinuierliche Integration (CI)
name: Java CI mit Maven

# Ausführung: Push oder Pull Request auf Main
on:
  push:
    branches: [ "CI-Pipeline_Vitaldaten", "main" ]
  pull_request:
    branches: [ "main" ]

# Ausführen des Auftrags
jobs:
  #Building
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  # Test
  test:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: maven
        - name: test
          run: mvn test
        - name: MVN-Site
          run: mvn site